### ISSUE TITLE
Feedback on assignment 1

### ISSUE THREAD

**Issue by csarven** [Nadine47/WBTC2015#1]
Why www as opposed to no-www?

What's the difference between `http://www.nadineneuen.ch/home` and `http://www.nadineneuen.ch/`?

Why `http://www.nadineneuen.ch/aboutme` and not `http://www.nadineneuen.ch/about-me` or `http://www.nadineneuen.ch/about` or `http://www.nadineneuen.ch/listenupfolksthispageisaboutmeokthanksbye`? Similarly why `http://www.nadineneuen.ch/interested_in` and not `http://www.nadineneuen.ch/interestedin`... ?

Why `interested_in` and not `experience_in`?

Is `http://www.nadineneuen.ch/aboutme` what you are suggesting as a way to refer for you?

`/links` is for further information about what? Anything? Random links?

**Comment by Nadine47** [comment]
Explenations Exercise 1: 

For me the difference between http://www.nadineneuen.ch/home and http://www.nadineneuen.ch/ is: 
I see http://www.nadineneuen.ch/ as my landing page (welcome page). 
the /home page is the first page, which includes the latest posts and quotations. 

I've chosen /aboutme because it substantiate that I'm speaking about me (and exclusives all the others). I wrote it without -/_ because it's easier for remember. 

I definied /intrested_in because it seemed logical from a gramatically base. For /experience it seemed not necessary for the mentioned  reason. 

/links is for any further information about my friends or sponsors (maybe I will have one once :-))

**Comment by csarven** [comment]
While there is nothing particularly wrong with having a welcome and a separate first page, it is sort of an "old" practice on the Web. Nowadays, http://www.nadineneuen.ch/ would simply be the "entry" point, and that's it. Don't forget that the site doesn't need to have a particular sequence (first page, second page..).

My comment about `/aboutme` and `interested_in` was that, you use two words in both cases, yet, the pattern you chose for them is different. Again, this is not wrong, it is just rather inconsistent. For example, if I know that your the terms in your URIs are separated by `-`s then that is the only thing I need to remember for all cases. If you said you have an article about "a how to guide for wbtc exercises", then it would be trivial to come up with `a-how-to-guide-for-wbtc-exercises`. I would not have to figure out somehow where `-`, `_`, or some other separator applies and where not. For additional background, check this out (which can get complicated, but it is an important aspect of Web architecture): http://tools.ietf.org/html/rfc6570
