### ISSUE TITLE
Feedback on assignment 2

### ISSUE THREAD

**Issue by csarven** [Nadine47/WBTC2015#2]
Is `<http://nadineneuen.ch/aboutme>` a document (e.g., `foaf:Document`) or a (e.g., `foaf:Person`)? I suggest making a statement giving the class it belongs to. You can have more than one but they should not conflict.

Make sure to end your N-Triple/Turtle statements with a period `.`. Turtle has some shortcuts if you prefer. See also: http://www.w3.org/TR/turtle/

What's `http://xmlns.com/foaf/0.1/accounts`? Can you show me its definition so I can read about it? I didn't see it in the FOAF vocabulary. Same goes for `knows`, `experiences`, `education`, and `travel`. What do they mean?

A statement like `<http://nadineneuen.ch/links> <http://xmlns.com/foaf/0.1/knows> <https://www.facebook.com/dena.sargent.79?fref=ts>` hints to me something like "the document about links knows the document about Dena`. I emphasize the word "document" here because they are both documents. I do not think`foaf:knows`is for documents, but I'd like to get your response on that. Same goes for the other statements e.g.,`http://nadineneuen.ch/intrested_in/hobbies http://xmlns.com/foaf/0.1/interests http://en.wikipedia.org/wiki/Skiing`. It sounds like your hobbies page has interest in Skiing. ;)

**Comment by Nadine47** [comment]
According to the information in todays lecture I tried to correct my exercise 2. 

http://nadineneuen.ch/aboutme 
foaf:Person; 
foaf:name "Nadine Neuenschwander" 
foaf:mbox "nadine@bfh.ch"

For http://xmlns.com/foaf/0.1/knows  I've found this on the web: http://xmlns.com/foaf/spec/#term_knows (isn't this specified?)

For: /accounts it should be /account (http://xmlns.com/foaf/spec/#term_account)

 /experiences, /education, /travel there isn't any definition (I've just invented them, because I didn't know better, sorry for that) 

and for the last question I guess that @prefix hobbies should be @prefix wikipedia : http://en.wikipedia.org/wiki/ 
and then for discribing hobbies --> 
     foaf:hobbies wikipedia:Skiing;

**Comment by csarven** [comment]
For `foaf:mbox`, we are expected to use an URI (See http://xmlns.com/foaf/spec/#term_mbox ), and "typically identified using the mailto: URI scheme". So: it should be `<mailto:nadine@bfh.ch>` instead of `"nadine@bfh.ch"`. One of them is an IRI and the other is a string.

Sorry, I don't know why I wrote 'knows`. That's fine.

As for inventing new terms, we usually do them under a Web space that we control. It doesn't help anyone when we define a new term somewhere out there but there is nothing to show for it when a machine goes there to look up for its definition.

Again, there is no such thing as `foaf:hobbies`! ;)

What you can say using the FOAF vocabulary is `foaf:interest wikipedia:Skiing` (assuming your subject resource of course).

Update your exercise file based on what's mentioned in this comment, and feel free to close this issue.
